# baseurl: /avishvj.github.io
title: Machine Learning for Precision Medicine
author: Avish Vijayaraghavan
simple_search: http://google.com/search
description: My personal website for work and blogging
name: tufte
personal_tag: avishvj

markdown: kramdown
permalink: /blog/:categories/:title
timezone: Europe/London

excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md'] # exclude from production site

plugins: ['jekyll/scholar', 'jekyll-include-cache']

#plugins: # used to be called gems
#  - jekyll-feed
#  - jekyll-scholar
#  - jekyll-include-cache

scholar:
  source: ./_bibliography
  bibliography: refs.bib

post:
  template: templates/_post.txt
  extension: md

page:
  template: templates/_page.txt
  extension: md

git:
  branch: master