#baseurl: /tufte-jekyll
title: Machine Learning for Precision Medicine
#subtitle: maybe add later?
author: Avish Vijayaraghavan
simple_search: http://google.com/search
description: My personal website for work and my blogs
url: "http://avishvj.github.io"


name: tufte

#personal tags for other websites
twitter_username: avishvj
github_username: avishvj

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: Europe/London

excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
#transfer:
#  command: rsync
#  settings: -av
#  source: _site/
#  destination: ~/Git/clayh53.github.com/
